#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

$HOME/Scripts/compon.sh picom &
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"
nvidia-settings --load-config-only &
dunst &
nm-applet &
$HOME/Scripts/runPasystray.sh
feh --bg-fill $HOME/Imagens/Wallpapers/arch.png &
/usr/bin/emacs --daemon &
$SCRIPTPATH/polybarLaunch.sh &
